export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST"
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS"
export const GET_BLOG_FAILURE = "GET_BLOG_FAILURE"


export const DETAIL_BLOG_REQUEST = "DETAIL_BLOG_REQUEST"
export const DETAIL_BLOG_SUCCESS = "DETAIL_BLOG_SUCCESS"
export const DETAIL_BLOG_FAILURE = "DETAIL_BLOG_FAILURE"

export const BLOG_SAVE_REQUEST = "BLOG_SAVE_REQUEST"
export const BLOG_SAVE_SUCCESS = "BLOG_SAVE_SUCCESS"
export const BLOG_SAVE_FAIL = "BLOG_SAVE_FAIL"

export const BLOG_DELETE_REQUEST = "BLOG_DELETE_REQUEST"
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS"
export const BLOG_DELETE_FAIL = "BLOG_DELETE_FAIL"

export const GET_CAT_REQUEST = "GET_CAT_REQUEST"
export const GET_CAT_SUCCESS = "GET_CAT_SUCCESS"
export const GET_CAT_FAILURE = "GET_CAT_FAILURE"