export const GALLERY_LIST_REQUEST = "GALLERY_LIST_REQUEST"
export const GALLERY_LIST_SUCCESS = "GALLERY_LIST_SUCCESS"
export const GALLERY_LIST_FAIL = "GALLERY_LIST_FAIL"

export const GALLERY_SAVE_REQUEST = "GALLERY_SAVE_REQUEST"
export const GALLERY_SAVE_SUCCESS = "GALLERY_SAVE_SUCCESS"
export const GALLERY_SAVE_FAIL = "GALLERY_SAVE_FAIL"

export const GALLERY_DELETE_REQUEST = "GALLERY_DELETE_REQUEST"
export const GALLERY_DELETE_SUCCESS = "GALLERY_DELETE_SUCCESS"
export const GALLERY_DELETE_FAIL = "GALLERY_DELETE_FAIL"