export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST"
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS"
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL"

export const SINGLEPROJECT_LIST_REQUEST = "SINGLEPROJECT_LIST_REQUEST"
export const SINGLEPROJECT_LIST_SUCCESS = "SINGLEPROJECT_LIST_SUCCESS"
export const SINGLEPROJECT_LIST_FAIL = "SINGLEPROJECT_LIST_FAIL"

export const PROJECT_SAVE_REQUEST = "PROJECT_SAVE_REQUEST"
export const PROJECT_SAVE_SUCCESS = "PROJECT_SAVE_SUCCESS"
export const PROJECT_SAVE_FAIL = "PROJECT_SAVE_FAIL"

export const PROJECT_DELETE_REQUEST = "PROJECT_DELETE_REQUEST"
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS"
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL"